language: node_js
node_js:
- 0.10

before_install:
  - sudo apt-get update
  - sudo apt-get install nginx
  - sudo chmod a+rw /var/log/nginx/error.log

notifications:
  email:
  - damon.oehlman@gmail.com
